baseurl: "/me"
url: "https://santimanuelr.github.io"
title: Santi Rodr√≠guez
description: Fullstack developer.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
url_linkedin: https://ar.linkedin.com/in/santiago-manuel-rodr%C3%ADguez-2532ba28
mail: mailto:santimanuelr@gmail.com